package com.diatomicsoft.culturalfoods.model.db

import androidx.lifecycle.MutableLiveData
import com.diatomicsoft.culturalfoods.R
import com.diatomicsoft.culturalfoods.model.data.Food

class DB {
    var dataLis = ArrayList<Food>()
    init {
        dataLis.add(Food(0, 5.0F,"Peking Roasted Duck", R.drawable.one,"Beijing Roasted DuckBeijing Roasted Duck\n" +
                "Peking duck (北京烤鸭 Běijīng kǎoyā) is a famous dish from Beijing, enjoying world fame, and considered as one of China national dishes. Peking duck is savored for its thin and crispy skin. Sliced Peking duck is often eaten with pancakes, sweet bean sauce, or soy sauce with mashed garlic. It is a must-taste dish in Beijing!\n" +
                "\n" +
                "As “the first dish to taste in China”, Beijing Roast Duck used to be a royal dish in medieval China. It has been a “national dish of diplomacy” since the 1970s, when it was first used for the reception of foreign guests by Premier Zhou Enlai (the first Premier of the People's Republic of China). It is highly praised by heads of state, government officials, and domestic and foreign tourists."))
        dataLis.add(Food(1, 0F,"Kung Pao Chicken", R.drawable.two,"Kung Pao ChickenKung Pao Chicken\n" +
                "Kung Pao Chicken (宫保鸡丁 gōngbào jīdīng) is a famous Sichuan-style specialty, popular with both Chinese and foreigners. The major ingredients are diced chicken, dried chili, cucumber, and fried peanuts (or cashews).People (Chinese takeaways) in Western countries have created a Western-style kung pao chicken, for which the diced chicken is covered with cornstarch, and vegetables, sweet and sour sauce, and mashed garlic are added. See How to Cook Kung Pao Chicken for a classic recipe and its history."))
        dataLis.add(Food(2, 0F,"Sweet and Sour Pork", R.drawable.three,"Sweet and Sour PorkSweet and Sour Pork\n" +
                "Sweet and sour pork (糖醋里脊 tángcù lǐjǐ) has a bright orange-red color, and a delicious sweet and sour taste. At the very beginning there was only sweet and sour pork, but to meet demands, there have been some developments on this dish. Now, the pork can be substituted with other ingredients like chicken, beef, or pork ribs."))
        dataLis.add(Food(3,0F,"Hot Pot", R.drawable.four,"Hot PotHot Pot\n" +
                "Hot pot, or hotpot (火锅 huǒguō), is one of the most popular dishes in China, especially in Sichuan Province or Chongqing. People cook in and eat from a simmering pot of soup stock (broth) on a gas/induction hob in the middle of the dining table with foodstuffs and condiments around the pot. People can add and cook whatever they like in the broth. The secret of whether a hot pot is good or not lies in the broth, which all the meat slices and vegetables take their flavor from.Chinese people are very fond of hot pot. In the past hot pot used to be favored only in winter, but nowadays hot pot has been appearing on tables all year round. It is a great way to socialize with friends and relatives. People gather around the pot to eat while chatting, eating, drinking, and having fun."))
        dataLis.add(Food(4,0F,"Dim Sum", R.drawable.five,"Dim SumCantonese Dim Sum\n" +
                "Dim sum (点心 diǎnxin) is one of the most popular Cantonese cuisine dishes. It contains a large range of small dishes, including dumplings, rolls, cakes, and meat, seafood, dessert, and vegetable preparations. There are more than one thousand dim sum dishes in existence today.Dim sum originated in Guangzhou city. People of Guangdong are fond of drinking tea in the morning or lunch. So, they often eat dim sum during their tea parties for breakfast and lunch. It is a popular way to get together with friends and relatives or have social gatherings. Read more about Dim sum."))
        dataLis.add(Food(5,0F,"Dumplings", R.drawable.six,"DumplingsDumplings\n" +
                "Dumplings (饺子 jiǎozi) are a traditional food type that is widely popular, especially in North China. Chinese dumplings consist of minced meat and/or chopped vegetables wrapped in a thin dough skin. Popular fillings are minced pork, diced shrimp, ground chicken, beef, and vegetables. Dumplings can be cooked by boiling, steaming, or frying.\n" +
                "\n" +
                "Dumplings are also a traditional dish eaten on Chinese New Year’s Eve. As they look like Chinese silver ingots (Chinese money in old times), it is believed that the more dumplings you eat during the New Year celebrations, the more money you will make in the New Year. Making dumplings is a good way to interact with your friends and relatives. You will see a busy kitchens with Chinese families making dumplings during Chinese New Year. Read more abou Dumplings."))
        dataLis.add(Food(6,0F,"Ma Po Tofu", R.drawable.seven,"Ma Po TofuMa Po Tofu\n" +
                "Ma Po tofu (麻婆豆腐 Mápó dòufǔ ‘Pockmarked Granny beancurd’) is one of the most famous dishes in Chuan Cuisine (Sichuan food) with a history of more than 100 years. It consists of beancurd along with some minced meat (pork or beef) in a spicy sauce. The sauce is made from fermented black beans and chili paste (douban/douchi).\n" +
                "\n" +
                "The inventor of Ma Po tofu was from Chengdu, Sichuan province. She was a grandma whose surname was Chen. It is said that Chen’s face was very pockmarked. In Chinese, ma means ‘pockmarked’ and 'po’ means grandma, and so people called the dish she made Ma Po ('Pockmarked Granny’) tofu. Her spicy and fragrant dish later became a highly popular item. It was introduced to Japan and also became a popular dish there. Read more about how to cook Ma Po Tofu.\n"))
        dataLis.add(Food(7,0F,"Char Siu", R.drawable.eight,"Char SiuCantonese Char Siu\n" +
                "In Cantonese, char means ‘fork’ and siu means ‘to roast’, so char sui (叉烧 chāshāo) means “fork roasted”. It is a kind of Cantonese roast pork. It is eaten\n" +
                "Saif\n" +
                "Saif Ahmed\n" +
                "with rice or noodles. It is also used as a filling in baozi (a kind of steamed stuffed bun)."))
        dataLis.add(Food(8,0F,"Chow Mein", R.drawable.nine,"Chow Mein\n" +
                "Chow mein is the Cantonese pronunciation of the Mandarin chǎomiàn (炒面), which means ‘stir-fried noodles’. This stir-fried dish consists of noodles, meat (usually chicken, beef, shrimp, or pork), onions, and celery.For making chow mein, the noodles need to be cooked in boiling water for a while. After they cool comes the step of stir-frying.There is an interesting story about the origin of chow mein. It is said that chow mein was invented by a woman called Shan Gu in Jiangsu Province. She was making food for workers who were building a great dam to prevent flooding of the Yellow River. She found that food went bad easily and fast in the hot weather. So, she invented chow mein, which can be kept for a longer time and is easily reheated and eaten. Since then, stir-frying has become a popular way of cooking noodles."))
        dataLis.add(Food(9,0F,"Fried Rice", R.drawable.ten,"Fried rice (炒饭 chǎofàn) is a dish made from fried cooked rice and other ingredients, often including eggs, vegetables, seafood, or meat. Fried rice is one of the most common Chinese foods. It is easy to make fried rice at home using leftover rice and other meat or vegetables from the last meal.It was said that an important diplomatic official in the late Qing Dynasty (1644–1912), Li Hongzhang, ordered his chef to cook a dish that both Chinese people and foreigners would like. The chef made fried rice, which was enjoyed by both the foreign guests and officials.The most famous fried rice in China is Yangzhou fried rice. Typical Yangzhou fried rice ingredients include shrimp, eggs, and barbecued pork.\n"))
        dataLis.add(Food(10,0F,"Twice-Cooked Pork Slices", R.drawable.elevan,"Twice-Cooked Pork SlicesTwice-Cooked Pork Slices.Twice-cooked pork or double-cooked pork (回锅肉 huíguōròu) is one of the most famous Sichuan pork dishes. Its Chinese name is huiguorou, which means ‘returned-to-the-pot meat’. Pork is boiled in the pot first. Then it is cooked again with other ingredients, including broad bean paste (doubanjiang), fermented black soybeans (douchi), garlic, ginger, and so on.It was said that the dish was created by a Chinese poet called Su Dongpo (a.k.a. Su Shi) in the Song Dynasty era (960–1279).Su made a delicious pork dish for his friends one day. He was boiling pork in a pot and walked out of the house and forgot about it. After he returned, he found the simmering pork had turned very soft. He tasted the pork sizzling in its fat and found the pork had become softer and more delicious than with his previous boiling method. So, he returned it to the pot with the other ingredients and impressed his friends with it.Due to its origin story and its taste, ‘twice-cooked pork’ has become very popular.\n"))
        dataLis.add(Food(11,0F,"Sichuan Pork", R.drawable.twelve,"Sichuan pork, or ‘poached pork slices’ (水煮肉片 shuǐzhǔ ròupiàn), is a famous Sichuan cuisine dish. Pork, with a coating made from egg-white and starch to preserve its freshness and tenderness, is boiled in broth. The meaty broth is typical Sichuan cuisine, featuring a peppery and spicy taste. When eating, you’ll find each piece of meat contains abundant juices with a fresh and fragrant spicy aroma.\n" +
                "\n" +
                "Poached beef slices is a popular version of this dish that we have a recipe for.\n"))
        dataLis.add(Food(12,0F,"Xiaolongbao", R.drawable.thirdten,"Xiǎolóngbāo (小笼包 ‘small basket buns’) are a kind of baozi (Chinese steamed bun). They are popular in Jiangsu and Shanghai. Xiaolongbao are traditionally cooked in a small bamboo basket, which gives them their name. The most common xiaolongbao filling is pork. Other ingredients can include beef, crab meat, shrimp, seafood, and vegetable fillings.\n" +
                "\n" +
                "There is a special way to eat the broth-filled Shanghai steamed-pork xiaolongbao (Shanghai soup buns): you can nibble off a small corner of dough and suck out the delicious soup. Or you can use a straw to suck the soup then eat the fillings and dough."))
        dataLis.add(Food(13,0F,"Zhajiangmian", R.drawable.fourten,"Zhajiangmian (炸酱面 /jaa-jyang-myen/ ‘fried sauce noodles’) is one of the most popular Shandong Cuisine dishes. It is a thick wheat noodle dish topped with zhajiang sauce. The sauce is made by simmering pork or beef with salty fermented soybean paste. In Chinese, zhajiang means ‘fried sauce’, while mian means ‘noodles’. It is also a well-known small meal or snack in Beijing.\n" +
                "\n" +
                "Originating in Shandong, zhajiangmian was introduced to Beijing by Qing Dynasty Emperor Guangxu (r. 1871–1908) and Empress Dowager Cixi during a trip from Beijing to Xi’an. They went into a restaurant and ordered a bowl of zhajiangmian. Both found it so tasty that they had to eat another bowl. Then, Empress Dowager Cixi brought the chef who made the ‘fried sauce noodles’ to the palace in Beijing. From then on, zhajiangmian became more and more popular in Beijing and around China."))
        dataLis.add(Food(14,0F,"Wonton Soup", R.drawable.sixten,"Wontons (馄炖 húndùn) are a kind of Chinese dumpling. Different from jiaozi, wontons have less filling and\n" +
                "are wrapped in much thinner dough wrappers. The shapes of wontons can be different depending on how they’re made. Some of them look like silver ingots, making them an auspicious ‘wealth-invoking’ dish.Wonton fillings are most often minced pork or diced shrimp. Wontons are commonly boiled and served in a soup (broth), but sometimes deep-fried"))
    }
}